const Alarm = "Alarm"
const AirQualitySensor = "AirQualitySensor"
const BarometricPressureSensor = "BarometricPressureSensor"
const BinarySensor = "BinarySensor"
const Camera = "Camera"
const ColorControl = "ColorControl"
const ColorSensor = "ColorSensor"
const DoorSensor = "DoorSensor"
const EnergyMonitor = "EnergyMonitor"
const HumiditySensor = "HumiditySensor"
const LeakSensor = "LeakSensor"
const Light = "Light"
const Lock = "Lock"
const MotionSensor = "MotionSensor"
const MultiLevelSensor = "MultiLevelSensor"
const MultiLevelSwitch = "MultiLevelSwitch"
const OnOffSwitch = "OnOffSwitch"
const PushButton = "PushButton"
const SmartPlug = "SmartPlug"
const SmokeSensor = "SmokeSensor"
const TemperatureSensor = "TemperatureSensor"
const Thermostat = "Thermostat"
const VideoCamera = "VideoCamera"


export const drawerWidth = 240;