### trune on
PUT http://localhost:9090/things/0x0000000010e2fa00/properties/on
Content-Type: application/x-www-form-urlencoded

true

### trune level
PUT http://localhost:9090/things/0x0000000010e2fa00/properties/level
Content-Type: application/x-www-form-urlencoded

100

### set hue
PUT http://localhost:9090/things/0x0000000010e2fa00/properties/hue
Content-Type: application/x-www-form-urlencoded

"#FF0000"


### trune off
PUT http://localhost:9090/things/0x0000000010e2fa00/properties/on
Content-Type: application/x-www-form-urlencoded

false

###GET Things
GET http://localhost:9090/things
Accept: application/json


### Delete thing
DELETE http://localhost:9090/things/0x0000000010e2fa00

###create thing
POST http://localhost:9090/things
Content-Type: application/json

{
  "@context": "https://webthings.io/schemas",
  "title": "0x0000000010e2fa00",
  "id": "0x0000000010e2fa00",
  "@type": [
    "Light"
  ],
  "support": "liuguilin361@gmai.com",
  "version": {
    "instance": "1.1",
    "model": ""
  },
  "created": "2021-12-20T00:57:40.5020687+08:00",
  "modified": "2021-12-20T00:57:40.5020687+08:00",
  "properties": {
    "hue": {
      "@type": "ColorProperty",
      "title": "Hue",
      "forms": [
        {
          "href": "/things/0x0000000010e2fa00/properties/hue"
        }
      ],
      "type": "string"
    },
    "level": {
      "@type": "BrightnessProperty",
      "title": "Brightness",
      "forms": [
        {
          "href": "/things/0x0000000010e2fa00/properties/level"
        }
      ],
      "unit": "percent",
      "type": "integer",
      "minimum": 0,
      "maximum": 100
    },
    "on": {
      "@type": "OnOffProperty",
      "title": "On/Off",
      "forms": [
        {
          "href": "/things/0x0000000010e2fa00/properties/on"
        }
      ],
      "type": "boolean"
    }
  },
  "actions": {
    "effect": {
      "forms": [
        {
          "href": "things/0x0000000010e2fa00/actions/effect",
          "op": "observeallproperties"
        }
      ]
    }
  },
  "pin": {
    "required": false,
    "pattern": ""
  }
}



###create thing action
POST http://localhost:9090/things/0x0000000010e2fa00/actions
Content-Type: application/json

{
  "effect": {"input": {"type": "smooth","duration": 100}}
}


<> 2021-12-11T003053.400.txt

### Get addonsInfo
GET http://localhost:9090/settings/addonsInfo
Accept: application/json

###GET Things
GET http://localhost:9090/things
Accept: application/json







