### trune on
PUT http://localhost:9090/things/192.168.1.103:55443/properties/on
Content-Type: application/x-www-form-urlencoded

true

### trune off
PUT http://localhost:9090/things/192.168.1.103:55443/properties/on
Content-Type: application/x-www-form-urlencoded

false

### trune level
PUT http://localhost:9090/things/192.168.1.103:55443/properties/bright
Content-Type: application/x-www-form-urlencoded

44

### set hue
PUT http://localhost:9090/things/192.168.1.103:55443/properties/color
Content-Type: application/x-www-form-urlencoded

"0000FF"

###GET Things
GET http://localhost:9090/things
Accept: application/json


### Delete thing
DELETE http://localhost:9090/things/192.168.1.103:55443

###create thing
POST http://localhost:9090/things
Content-Type: application/json

{
  "@context": "https://webthings.io/schemas",
  "title": "192.168.1.103:55443",
  "id": "192.168.1.103:55443",
  "@type": [
    "",
    "Light",
    "OnOffSwitch"
  ],
  "support": "liuguilin361@gmai.com",
  "version": {
    "instance": "1.1",
    "model": ""
  },
  "properties": {
    "color": {
      "@type": "ColorProperty",
      "forms": [
        {
          "href": "/things/192.168.1.103:55443/properties/color"
        }
      ],
      "type": "string"
    },
    "on": {
      "@type": "OnOffProperty",
      "forms": [
        {
          "href": "/things/192.168.1.103:55443/properties/on"
        }
      ],
      "type": "boolean"
    },
    "bright": {
      "@type": "BrightnessProperty",
      "forms": [
        {
          "href": "/things/192.168.1.103:55443/properties/bright"
        }
      ],
      "unit": "percentage",
      "type": "integer",
      "minimum": 0,
      "maximum": 100
    }
  }
}

###create rule
POST http://localhost:9090/rules
Content-Type: application/json

{
  "name": "testRule",
  "enabled": true,
  "trigger": {
    "property": {
      "type": "boolean",
      "id": "on",
      "thing": "light1"
    },
    "type": "BooleanTrigger",
    "onValue": true
  },
  "effect": {
    "property": {
      "type": "boolean",
      "thing": "192.168.1.103:55443",
      "id": "on"
    },
    "type": "SetEffect",
    "value": true
  }
}

###create time rule
POST http://localhost:9090/rules
Content-Type: application/json

{
  "name": "testRule",
  "enabled": true,
  "trigger": {
    "time": "3:17",
    "type": "TimeTrigger",
    "onValue": true
  },
  "effect": {
    "property": {
      "type": "boolean",
      "thing": "light2",
      "id": "on"
    },
    "type": "PulseEffect",
    "value": true
  }
}

###create thing
POST http://localhost:9090/things
Content-Type: application/json


{
  "@context": "https://webthings.io/schemas",
  "title": "0x0000000010e2fa00",
  "id": "0x0000000010e2fa00",
  "@type": [
    "Light"
  ],
  "support": "liuguilin361@gmai.com",
  "version": {
    "instance": "1.1",
    "model": ""
  },
  "properties": {
    "level": {
      "title": "Brightness",
      "forms": [
        {
          "href": "/things/0x0000000010e2fa00/properties/level"
        }
      ],
      "unit": "percent",
      "type": "integer",
      "minimum": 0,
      "maximum": 0,
      "multipleOf": 0
    },
    "hue": {
      "title": "Hue",
      "forms": [
        {
          "href": "/things/0x0000000010e2fa00/properties/hue"
        }
      ],
      "type": "string",
      "minLength": 0
    },
    "on": {
      "title": "On/Off",
      "forms": [
        {
          "href": "/things/0x0000000010e2fa00/properties/on"
        }
      ],
      "type": "boolean"
    }
  },
  "actions": {
    "effect": {
      "forms": [
        {
          "href": "things/0x0000000010e2fa00/actions/effect",
          "op": [
            "observeallproperties"
          ]
        }
      ]
    }
  },
  "pin": {
    "required": false,
    "pattern": ""
  }
}




###create thing action
POST http://localhost:9090/things/0x0000000010e2fa00/actions
Content-Type: application/json

{
  "effect": {
    "input": {
      "type": "smooth",
      "duration": 100
    }
  }
}


<> 2021-12-11T003053.400.txt

### Get addonsInfo
GET http://localhost:9090/settings/addonsInfo
Accept: application/json

###GET Things
GET http://localhost:9090/things
Accept: application/json







