### trune on
PUT http://localhost:9090/things/192.168.1.105:55443/properties/on
Content-Type: application/x-www-form-urlencoded

true

### trune level
PUT http://localhost:9090/things/192.168.1.105:55443/properties/level
Content-Type: application/x-www-form-urlencoded

100

### set hue
PUT http://localhost:9090/things/192.168.1.105:55443/properties/color
Content-Type: application/x-www-form-urlencoded

"#0000FF"


### trune off
PUT http://localhost:9090/things/192.168.1.105:55443/properties/on
Content-Type: application/x-www-form-urlencoded

false

###GET Things
GET http://localhost:9090/things
Accept: application/json


### Delete thing
DELETE http://localhost:9090/things/192.168.1.105:55443

###create thing
POST http://localhost:9090/things
Content-Type: application/json

{
  "@context": "https://webthings.io/schemas",
  "title": "192.168.1.105:55443",
  "id": "192.168.1.105:55443",
  "@type": [
    "Light",
    "OnOffSwitch"
  ],
  "support": "liuguilin361@gmai.com",
  "version": {
    "instance": "1.1",
    "model": ""
  },
  "properties": {
    "color": {
      "forms": [
        {
          "href": "/things/192.168.1.105:55443/properties/color"
        }
      ],
      "type": "string",
      "minLength": 0
    },
    "level": {
      "forms": [
        {
          "href": "/things/192.168.1.105:55443/properties/level"
        }
      ],
      "type": "integer",
      "minimum": 0,
      "maximum": 0,
      "multipleOf": 0
    },
    "on": {
      "forms": [
        {
          "href": "/things/192.168.1.105:55443/properties/on"
        }
      ],
      "type": "boolean"
    }
  }
}



###create thing action
POST http://localhost:9090/things/0x0000000010e2fa00/actions
Content-Type: application/json

{
  "effect": {
    "input": {
      "type": "smooth",
      "duration": 100
    }
  }
}


<> 2021-12-11T003053.400.txt

### Get addonsInfo
GET http://localhost:9090/settings/addonsInfo
Accept: application/json

###GET Things
GET http://localhost:9090/things
Accept: application/json







