// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: servicesMessage.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceSetPropertyValueRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageType                                 `protobuf:"varint,1,opt,name=messageType,proto3,enum=plugin.MessageType" json:"messageType,omitempty"`
	Data        *ServiceSetPropertyValueRequestMessage_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceSetPropertyValueRequestMessage) Reset() {
	*x = ServiceSetPropertyValueRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceSetPropertyValueRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSetPropertyValueRequestMessage) ProtoMessage() {}

func (x *ServiceSetPropertyValueRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSetPropertyValueRequestMessage.ProtoReflect.Descriptor instead.
func (*ServiceSetPropertyValueRequestMessage) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceSetPropertyValueRequestMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_PluginRegisterRequest
}

func (x *ServiceSetPropertyValueRequestMessage) GetData() *ServiceSetPropertyValueRequestMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceGetThingsRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageType                          `protobuf:"varint,1,opt,name=messageType,proto3,enum=plugin.MessageType" json:"messageType,omitempty"`
	Data        *ServiceGetThingsRequestMessage_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceGetThingsRequestMessage) Reset() {
	*x = ServiceGetThingsRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingsRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingsRequestMessage) ProtoMessage() {}

func (x *ServiceGetThingsRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingsRequestMessage.ProtoReflect.Descriptor instead.
func (*ServiceGetThingsRequestMessage) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceGetThingsRequestMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_PluginRegisterRequest
}

func (x *ServiceGetThingsRequestMessage) GetData() *ServiceGetThingsRequestMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceGetThingsResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageType                           `protobuf:"varint,1,opt,name=messageType,proto3,enum=plugin.MessageType" json:"messageType,omitempty"`
	Data        *ServiceGetThingsResponseMessage_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceGetThingsResponseMessage) Reset() {
	*x = ServiceGetThingsResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingsResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingsResponseMessage) ProtoMessage() {}

func (x *ServiceGetThingsResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingsResponseMessage.ProtoReflect.Descriptor instead.
func (*ServiceGetThingsResponseMessage) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceGetThingsResponseMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_PluginRegisterRequest
}

func (x *ServiceGetThingsResponseMessage) GetData() *ServiceGetThingsResponseMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceGetThingRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageType                         `protobuf:"varint,1,opt,name=messageType,proto3,enum=plugin.MessageType" json:"messageType,omitempty"`
	Data        *ServiceGetThingRequestMessage_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceGetThingRequestMessage) Reset() {
	*x = ServiceGetThingRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingRequestMessage) ProtoMessage() {}

func (x *ServiceGetThingRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingRequestMessage.ProtoReflect.Descriptor instead.
func (*ServiceGetThingRequestMessage) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceGetThingRequestMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_PluginRegisterRequest
}

func (x *ServiceGetThingRequestMessage) GetData() *ServiceGetThingRequestMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceGetThingResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageType                          `protobuf:"varint,1,opt,name=messageType,proto3,enum=plugin.MessageType" json:"messageType,omitempty"`
	Data        *ServiceGetThingResponseMessage_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServiceGetThingResponseMessage) Reset() {
	*x = ServiceGetThingResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingResponseMessage) ProtoMessage() {}

func (x *ServiceGetThingResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingResponseMessage.ProtoReflect.Descriptor instead.
func (*ServiceGetThingResponseMessage) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceGetThingResponseMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_PluginRegisterRequest
}

func (x *ServiceGetThingResponseMessage) GetData() *ServiceGetThingResponseMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServiceSetPropertyValueRequestMessage_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId     string `protobuf:"bytes,11,opt,name=pluginId,proto3" json:"pluginId,omitempty"`
	AdapterId    string `protobuf:"bytes,12,opt,name=adapterId,proto3" json:"adapterId,omitempty"`
	ThingId      string `protobuf:"bytes,13,opt,name=thingId,proto3" json:"thingId,omitempty"`
	PropertyName string `protobuf:"bytes,14,opt,name=propertyName,proto3" json:"propertyName,omitempty"`
	Value        []byte `protobuf:"bytes,15,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ServiceSetPropertyValueRequestMessage_Data) Reset() {
	*x = ServiceSetPropertyValueRequestMessage_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceSetPropertyValueRequestMessage_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceSetPropertyValueRequestMessage_Data) ProtoMessage() {}

func (x *ServiceSetPropertyValueRequestMessage_Data) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceSetPropertyValueRequestMessage_Data.ProtoReflect.Descriptor instead.
func (*ServiceSetPropertyValueRequestMessage_Data) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServiceSetPropertyValueRequestMessage_Data) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *ServiceSetPropertyValueRequestMessage_Data) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *ServiceSetPropertyValueRequestMessage_Data) GetThingId() string {
	if x != nil {
		return x.ThingId
	}
	return ""
}

func (x *ServiceSetPropertyValueRequestMessage_Data) GetPropertyName() string {
	if x != nil {
		return x.PropertyName
	}
	return ""
}

func (x *ServiceSetPropertyValueRequestMessage_Data) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ServiceGetThingsRequestMessage_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId     string `protobuf:"bytes,11,opt,name=pluginId,proto3" json:"pluginId,omitempty"`
	AdapterId    string `protobuf:"bytes,12,opt,name=adapterId,proto3" json:"adapterId,omitempty"`
	PropertyName string `protobuf:"bytes,14,opt,name=propertyName,proto3" json:"propertyName,omitempty"`
}

func (x *ServiceGetThingsRequestMessage_Data) Reset() {
	*x = ServiceGetThingsRequestMessage_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingsRequestMessage_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingsRequestMessage_Data) ProtoMessage() {}

func (x *ServiceGetThingsRequestMessage_Data) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingsRequestMessage_Data.ProtoReflect.Descriptor instead.
func (*ServiceGetThingsRequestMessage_Data) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ServiceGetThingsRequestMessage_Data) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *ServiceGetThingsRequestMessage_Data) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *ServiceGetThingsRequestMessage_Data) GetPropertyName() string {
	if x != nil {
		return x.PropertyName
	}
	return ""
}

type ServiceGetThingsResponseMessage_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId  string `protobuf:"bytes,11,opt,name=pluginId,proto3" json:"pluginId,omitempty"`
	AdapterId string `protobuf:"bytes,12,opt,name=adapterId,proto3" json:"adapterId,omitempty"`
	Things    []byte `protobuf:"bytes,14,opt,name=things,proto3" json:"things,omitempty"`
}

func (x *ServiceGetThingsResponseMessage_Data) Reset() {
	*x = ServiceGetThingsResponseMessage_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingsResponseMessage_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingsResponseMessage_Data) ProtoMessage() {}

func (x *ServiceGetThingsResponseMessage_Data) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingsResponseMessage_Data.ProtoReflect.Descriptor instead.
func (*ServiceGetThingsResponseMessage_Data) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ServiceGetThingsResponseMessage_Data) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *ServiceGetThingsResponseMessage_Data) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *ServiceGetThingsResponseMessage_Data) GetThings() []byte {
	if x != nil {
		return x.Things
	}
	return nil
}

type ServiceGetThingRequestMessage_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId  string `protobuf:"bytes,11,opt,name=pluginId,proto3" json:"pluginId,omitempty"`
	AdapterId string `protobuf:"bytes,12,opt,name=adapterId,proto3" json:"adapterId,omitempty"`
	ThingId   string `protobuf:"bytes,13,opt,name=thingId,proto3" json:"thingId,omitempty"`
}

func (x *ServiceGetThingRequestMessage_Data) Reset() {
	*x = ServiceGetThingRequestMessage_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingRequestMessage_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingRequestMessage_Data) ProtoMessage() {}

func (x *ServiceGetThingRequestMessage_Data) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingRequestMessage_Data.ProtoReflect.Descriptor instead.
func (*ServiceGetThingRequestMessage_Data) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ServiceGetThingRequestMessage_Data) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *ServiceGetThingRequestMessage_Data) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *ServiceGetThingRequestMessage_Data) GetThingId() string {
	if x != nil {
		return x.ThingId
	}
	return ""
}

type ServiceGetThingResponseMessage_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId  string `protobuf:"bytes,11,opt,name=pluginId,proto3" json:"pluginId,omitempty"`
	AdapterId string `protobuf:"bytes,12,opt,name=adapterId,proto3" json:"adapterId,omitempty"`
	Thing     []byte `protobuf:"bytes,14,opt,name=thing,proto3" json:"thing,omitempty"`
}

func (x *ServiceGetThingResponseMessage_Data) Reset() {
	*x = ServiceGetThingResponseMessage_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_servicesMessage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceGetThingResponseMessage_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceGetThingResponseMessage_Data) ProtoMessage() {}

func (x *ServiceGetThingResponseMessage_Data) ProtoReflect() protoreflect.Message {
	mi := &file_servicesMessage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceGetThingResponseMessage_Data.ProtoReflect.Descriptor instead.
func (*ServiceGetThingResponseMessage_Data) Descriptor() ([]byte, []int) {
	return file_servicesMessage_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ServiceGetThingResponseMessage_Data) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *ServiceGetThingResponseMessage_Data) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *ServiceGetThingResponseMessage_Data) GetThing() []byte {
	if x != nil {
		return x.Thing
	}
	return nil
}

var File_servicesMessage_proto protoreflect.FileDescriptor

var file_servicesMessage_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x1a,
	0x11, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xbd, 0x02, 0x0a, 0x25, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x0b,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x46, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x32, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x53, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x94, 0x01, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0xfe, 0x01, 0x0a, 0x1e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65,
	0x74, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3f, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x54, 0x68,
	0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x64, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49,
	0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0xf4, 0x01, 0x0a, 0x1f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47,
	0x65, 0x74, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x40,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74,
	0x54, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x1a, 0x58, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x22, 0xf2, 0x01, 0x0a, 0x1d, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x0b,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x1a, 0x5a, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x64, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x49, 0x64,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22,
	0xf0, 0x01, 0x0a, 0x1e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x54, 0x68,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3f, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x56, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x68, 0x69, 0x6e, 0x67, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x68, 0x69,
	0x6e, 0x67, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2e, 0x2f, 0x2e, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_servicesMessage_proto_rawDescOnce sync.Once
	file_servicesMessage_proto_rawDescData = file_servicesMessage_proto_rawDesc
)

func file_servicesMessage_proto_rawDescGZIP() []byte {
	file_servicesMessage_proto_rawDescOnce.Do(func() {
		file_servicesMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_servicesMessage_proto_rawDescData)
	})
	return file_servicesMessage_proto_rawDescData
}

var file_servicesMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_servicesMessage_proto_goTypes = []interface{}{
	(*ServiceSetPropertyValueRequestMessage)(nil),      // 0: plugin.ServiceSetPropertyValueRequestMessage
	(*ServiceGetThingsRequestMessage)(nil),             // 1: plugin.ServiceGetThingsRequestMessage
	(*ServiceGetThingsResponseMessage)(nil),            // 2: plugin.ServiceGetThingsResponseMessage
	(*ServiceGetThingRequestMessage)(nil),              // 3: plugin.ServiceGetThingRequestMessage
	(*ServiceGetThingResponseMessage)(nil),             // 4: plugin.ServiceGetThingResponseMessage
	(*ServiceSetPropertyValueRequestMessage_Data)(nil), // 5: plugin.ServiceSetPropertyValueRequestMessage.Data
	(*ServiceGetThingsRequestMessage_Data)(nil),        // 6: plugin.ServiceGetThingsRequestMessage.Data
	(*ServiceGetThingsResponseMessage_Data)(nil),       // 7: plugin.ServiceGetThingsResponseMessage.Data
	(*ServiceGetThingRequestMessage_Data)(nil),         // 8: plugin.ServiceGetThingRequestMessage.Data
	(*ServiceGetThingResponseMessage_Data)(nil),        // 9: plugin.ServiceGetThingResponseMessage.Data
	(MessageType)(0), // 10: plugin.messageType
}
var file_servicesMessage_proto_depIdxs = []int32{
	10, // 0: plugin.ServiceSetPropertyValueRequestMessage.messageType:type_name -> plugin.messageType
	5,  // 1: plugin.ServiceSetPropertyValueRequestMessage.data:type_name -> plugin.ServiceSetPropertyValueRequestMessage.Data
	10, // 2: plugin.ServiceGetThingsRequestMessage.messageType:type_name -> plugin.messageType
	6,  // 3: plugin.ServiceGetThingsRequestMessage.data:type_name -> plugin.ServiceGetThingsRequestMessage.Data
	10, // 4: plugin.ServiceGetThingsResponseMessage.messageType:type_name -> plugin.messageType
	7,  // 5: plugin.ServiceGetThingsResponseMessage.data:type_name -> plugin.ServiceGetThingsResponseMessage.Data
	10, // 6: plugin.ServiceGetThingRequestMessage.messageType:type_name -> plugin.messageType
	8,  // 7: plugin.ServiceGetThingRequestMessage.data:type_name -> plugin.ServiceGetThingRequestMessage.Data
	10, // 8: plugin.ServiceGetThingResponseMessage.messageType:type_name -> plugin.messageType
	9,  // 9: plugin.ServiceGetThingResponseMessage.data:type_name -> plugin.ServiceGetThingResponseMessage.Data
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_servicesMessage_proto_init() }
func file_servicesMessage_proto_init() {
	if File_servicesMessage_proto != nil {
		return
	}
	file_messageType_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_servicesMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceSetPropertyValueRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingsRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingsResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceSetPropertyValueRequestMessage_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingsRequestMessage_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingsResponseMessage_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingRequestMessage_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_servicesMessage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceGetThingResponseMessage_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_servicesMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_servicesMessage_proto_goTypes,
		DependencyIndexes: file_servicesMessage_proto_depIdxs,
		MessageInfos:      file_servicesMessage_proto_msgTypes,
	}.Build()
	File_servicesMessage_proto = out.File
	file_servicesMessage_proto_rawDesc = nil
	file_servicesMessage_proto_goTypes = nil
	file_servicesMessage_proto_depIdxs = nil
}
