ports:
  https: 4443
  http: 9090
  ipc: 9600

profileDir: "/Users/liuguilin/Documents/web-things/gateway/profile"

addonManager:
  listUrls:
    - "http://182.61.24.190:8443/addons"
  testAddons: false

database:
  logRotateDays: 30,
  removeBeforeOpen: false,
