ports:
  https: 4443
  http: 9090
  ipc: 9500

profileDir: "./profile"
gatewayVersion: "0.1.0"

addonManager:
  listUrls:
    - "http://182.61.24.190:8443/addon"
  testAddons: false

database:
  logRotateDays: 30,
  removeBeforeOpen: false,
