package properties

const (
	Brightness       = "brightness"
	Hue              = "hue"
	ColorTemperature = "ct"
	ColorModel       = "color_mode"

	TypeString  = "string"
	TypeBoolean = "boolean"
	TypeInteger = "integer"
	TypeNumber  = "number"

	UnitHectopascal = "hectopascal"
	UnitKelvin      = "kelvin"
	UnitPercentage  = "percentage"
	UnitArcDegrees  = "arcdegrees"
	UnitCelsius     = "celsius"
	UnitLux         = "lux"
	UnitSeconds     = "seconds"
	UnitPPM         = "ppm"

	Properties_AlarmProperty                    = "AlarmProperty"
	Properties_BarometricPressureProperty       = "BarometricPressureProperty"
	Properties_ColorProperty                    = "ColorProperty"
	Properties_ColorTemperatureProperty         = "ColorTemperatureProperty"
	Properties_ConcentrationProperty            = "ConcentrationProperty"
	Properties_CurrentProperty                  = "CurrentProperty"
	Properties_DensityProperty                  = "DensityProperty"
	Properties_FrequencyProperty                = "FrequencyProperty"
	Properties_HeatingCoolingProperty           = "HeatingCoolingProperty"
	Properties_HumidityProperty                 = "HumidityProperty"
	Properties_ImageProperty                    = "ImageProperty"
	Properties_InstantaneousPowerFactorProperty = "InstantaneousPowerFactorProperty"
	Properties_InstantaneousPowerProperty       = "InstantaneousPowerProperty"
	Properties_LeakProperty                     = "LeakProperty"
	Properties_LevelProperty                    = "LevelProperty"
	Properties_LockedProperty                   = "LockedProperty"
	Properties_MotionProperty                   = "MotionProperty"
	Properties_OnOffProperty                    = "OnOffProperty"
	Properties_OpenProperty                     = "OpenProperty"
	Properties_PushedProperty                   = "PushedProperty"
	Properties_SmokeProperty                    = "SmokeProperty"
	Properties_TargetTemperatureProperty        = "TargetTemperatureProperty"
	Properties_TemperatureProperty              = "TemperatureProperty"
	Properties_ThermostatModeProperty           = "ThermostatModeProperty"
	Properties_VideoProperty                    = "VideoProperty"
	Properties_VoltageProperty                  = "VoltageProperty"
)
