### trune on
PUT http://localhost:9090/things/192.168.1.101:55443/properties/on
Content-Type: application/x-www-form-urlencoded

true

### trun off
PUT http://localhost:9090/things/192.168.1.101:55443/properties/on
Content-Type: application/x-www-form-urlencoded

false

### trun bright
PUT http://localhost:9090/things/192.168.1.101:55443/properties/level
Content-Type: application/x-www-form-urlencoded

55

### set hue
PUT http://localhost:9090/things/192.168.1.101:55443/properties/color
Content-Type: application/x-www-form-urlencoded

"ffffff"

###GET Things
GET http://localhost:9090/things
Accept: application/json


### Delete thing
DELETE http://localhost:9090/things/12a00

###create thing
POST http://localhost:9090/things
Content-Type: application/json

{
  "@context": "https://webthings.io/schemas",
  "@type": [
    "Light",
    "OnOffSwitch"
  ],
  "id": "192.168.1.101:55443",
  "title": "Light192.168.1.101:55443",
  "properties": {
    "on": {
      "@type": "OnOffProperty",
      "forms": [
        {
          "href": "things/192.168.1.101:55443/properties/on",
          "contentType": "application/json",
          "op": [
            "readproperty",
            "writeproperty"
          ]
        }
      ],
      "type": "boolean"
    },
    "level": {
      "@type": "BrightnessProperty",
      "forms": [
        {
          "href": "things/192.168.1.101:55443/properties/level",
          "contentType": "application/json",
          "op": [
            "readproperty",
            "writeproperty"
          ]
        }
      ],
      "type": "integer",
      "minimum": 0,
      "maximum": 100
    },
    "color": {
      "@type": "ColorProperty",
      "forms": [
        {
          "href": "things/192.168.1.101:55443/properties/color",
          "contentType": "application/json",
          "op": [
            "readproperty",
            "writeproperty"
          ]
        }
      ],
      "type": "string"
    }
  },
  "forms": [
    {
      "href": "/things/192.168.1.101:55443/properties",
      "contentType": "application/json",
      "op": [
        "readallproperties"
      ]
    }
  ]
}







### Get addonsInfo
GET http://localhost:9090/settings/addonsInfo
Accept: application/json

###GET Things
GET http://localhost:9090/things
Accept: application/json







