### trune on
PUT http://localhost:9090/things/192.168.1.101:55443/properties/on
Content-Type: application/x-www-form-urlencoded

true

### trun off
PUT http://localhost:9090/things/192.168.1.101:55443/properties/on
Content-Type: application/x-www-form-urlencoded

false

### trun bright
PUT http://localhost:9090/things/192.168.1.101:55443/properties/bright
Content-Type: application/x-www-form-urlencoded

22

### set hue
PUT http://localhost:9090/things/192.168.1.101:55443/properties/color
Content-Type: application/x-www-form-urlencoded

"f000ff"

###GET Things
GET http://localhost:9090/things
Accept: application/json


### Delete thing
DELETE http://localhost:9090/things/192.168.1.101:55443

###create thing
POST http://localhost:9090/things
Content-Type: application/json

{
  "@context": "https://webthings.io/schemas",
  "title": "192.168.1.101:55443",
  "id": "192.168.1.101:55443",
  "@type": [
    "Light",
    "OnOffSwitch"
  ],
  "support": "liuguilin361@gmai.com",
  "version": {
    "instance": "1.1",
    "model": ""
  },
  "properties": {
    "color": {"@type":"ColorProperty","forms":[{"href":"/things/192.168.1.101:55443/properties/color"}],"type":"string"},
    "on": {"@type":"OnOffProperty","forms":[{"href":"/things/192.168.1.101:55443/properties/on"}],"type":"boolean"},
    "bright": {"@type":"BrightnessProperty","forms":[{"href":"/things/192.168.1.101:55443/properties/bright"}],"unit":"percentage","type":"integer","minimum":0,"maximum":100}
  }
}


###create thing action
POST http://localhost:9090/things/0x0000000010e2fa00/actions
Content-Type: application/json

{
  "effect": {
    "input": {
      "type": "smooth",
      "duration": 100
    }
  }
}


### Get addonsInfo
GET http://localhost:9090/settings/addonsInfo
Accept: application/json

###GET Things
GET http://localhost:9090/things
Accept: application/json







