### trune on
PUT http://192.168.1.106:9090/things/192.168.1.101:55443/properties/on
Content-Type: application/x-www-form-urlencoded

true

### trun off
PUT http://192.168.1.106:9090/things/192.168.1.101:55443/properties/on
Content-Type: application/x-www-form-urlencoded

false

### trun bright
PUT http://localhost:9090/things/192.168.1.101:55443/properties/bright
Content-Type: application/x-www-form-urlencoded

21

### set hue
PUT http://localhost:9090/things/192.168.1.101:55443/properties/color
Content-Type: application/x-www-form-urlencoded

"ff0000"

###GET Things
GET http://192.168.1.106:9090/things
Accept: application/json


### Delete thing
DELETE http://localhost:9090/things/192.168.1.101:55443

###create thing
POST http://localhost:9090/things
Content-Type: application/json

{
  "@context": "https://webthings.io/schemas",
  "title": "192.168.1.101:55443",
  "id": "192.168.1.101:55443",
  "@type": [
    "Light",
    "OnOffSwitch"
  ],
  "version": {
    "model": "1.0.0"
  },
  "properties": {
    "color": {
      "@type": "ColorProperty",
      "forms": [
        {
          "href": "/properties/color",
          "contentType": "application/json",
          "op": [
            "readproperty",
            "writeproperty"
          ]
        }
      ],
      "type": "string"
    },
    "on": {
      "@type": "OnOffProperty",
      "forms": [
        {
          "href": "/properties/on",
          "contentType": "application/json",
          "op": [
            "readproperty",
            "writeproperty"
          ]
        }
      ],
      "type": "boolean"
    },
    "bright": {
      "@type": "BrightnessProperty",
      "forms": [
        {
          "href": "/properties/bright",
          "contentType": "application/json",
          "op": [
            "readproperty",
            "writeproperty"
          ]
        }
      ],
      "unit": "percentage",
      "type": "integer",
      "minimum": 0,
      "maximum": 100
    }
  },
  "forms": [
    {
      "href": "/properties",
      "contentType": "application/json",
      "op": [
        "readallproperties"
      ]
    }
  ]
}




### Get addonsInfo
GET http://localhost:9090/settings/addonsInfo
Accept: application/json

###GET Things
GET http://localhost:9090/things
Accept: application/json







