package controllers

import (
	"github.com/galenliu/gateway/configs"
	"github.com/galenliu/gateway/pkg/bus"
	"github.com/galenliu/gateway/pkg/log"
	"github.com/galenliu/gateway/pkg/util"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/websocket/v2"
	// docs are generated by Swag CLI, you have to import them.
	_ "github.com/arsmn/fiber-swagger/v2/example/docs"

	//"gateway/server"
	"github.com/galenliu/gateway/server/models"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"net/http"
	"strconv"
)

type Config struct {
	HttpPort    int
	HttpsPort   int
	StaticDir   string
	TemplateDir string
	UploadDir   string
	LogDir      string
}

type Web struct {
	*fiber.App
	config Config
	things *models.Things
}

func NewWebAPP(opts ...WebOption) *Web {
	options := NewDefaultWebConfig()
	for _, o := range opts {
		o(&options)
	}
	web := Web{}
	web.things = models.NewThings()
	web.config = options
	web.App = CollectRoute(options)

	return &web
}

func CollectRoute(conf Config) *fiber.App {

	//init
	var app = fiber.New()
	app.Use(recover.New())

	//app.Use("/", filesystem.New(filesystem.Config{
	//	Root: http.FS(server.File),
	//}))

	//logger
	app.Use(logger.New())

	//ping controller
	app.Get("/ping", func(c *fiber.Ctx) error {
		return c.SendStatus(http.StatusNoContent)
	})

	//root handler
	app.Use(rootHandler)

	//app.Get("/", controllers.RootHandle())
	app.Static("/index.htm", "")

	actionsController := NewActionsController()
	thingsController := NewThingsControllerFunc()
	usersController := NewUsersController()
	addonController := NewAddonController()

	Tid := "/:thingId"

	//Things Controller
	{
		thingsGroup := app.Group(util.ThingsPath)
		//set a properties of a thing.
		thingsGroup.Put("/:thingId/properties/*", thingsController.handleSetProperty)
		thingsGroup.Get("/:thingId/properties/*", thingsController.handleGetProperty)

		//Handle creating a new thing.
		thingsGroup.Post("/", thingsController.handleCreateThing)

		thingsGroup.Get("/:thingId", thingsController.handleGetThing)
		thingsGroup.Get("/", thingsController.handleGetThings)

		thingsGroup.Get("/:thingId", websocket.New(handleWebsocket))
		thingsGroup.Get("/", websocket.New(handleWebsocket))

		//Get the properties of a thing
		thingsGroup.Get(Tid+util.PropertiesPath, thingsController.handleGetProperties)

		thingsGroup.Get(Tid+util.ActionsPath, actionsController.handleGetActions)
		thingsGroup.Post(Tid+util.ActionsPath, actionsController.handleAction)

		// Modify a ThingInfo.
		thingsGroup.Put("/:thingId", thingsController.handleSetThing)

		thingsGroup.Patch("/", thingsController.handlePatchThings)
		thingsGroup.Patch("/:thingId", thingsController.handlePatchThing)

		thingsGroup.Delete("/:thingId", thingsController.handleDeleteThing)

	}

	//NewThingFromString Controller
	{
		newThingsGroup := app.Group(util.NewThingsPath)
		newThingsGroup.Use("/", func(c *fiber.Ctx) error {
			if websocket.IsWebSocketUpgrade(c) {
				c.Locals("websocket", true)
				return c.Next()
			}
			return fiber.ErrUpgradeRequired
		})

		newThingsGroup.Get("/", websocket.New(func(conn *websocket.Conn) {
			handleNewThingsWebsocket(conn)
		}))
	}

	{
		usersGroup := app.Group(util.UsersPath)

		usersGroup.Get("/count", usersController.getCount)
		usersGroup.Post("/", usersController.createUser)
	}

	{ //Addons Controller
		addonGroup := app.Group(util.AddonsPath)
		addonGroup.Get("/", addonController.handlerGetAddons)
		addonGroup.Post("/", addonController.handlerInstallAddon)
		addonGroup.Put("/:addonId", addonController.handlerSetAddon)
		addonGroup.Patch("/:addonId", addonController.handlerUpdateAddon)
		addonGroup.Get("/:addonId/config", addonController.handlerGetAddonConfig)
		addonGroup.Put("/:addonId/config", addonController.handlerSetAddonConfig)
	}

	{ //settings Controller
		debugGroup := app.Group(util.SettingsPath)
		settingsController := NewSettingController()
		debugGroup.Get("/addonsInfo", settingsController.handleGetAddonsInfo)
	}

	{ //actions Controller
		actionsGroup := app.Group(util.ActionsPath)

		actionsGroup.Post("/", actionsController.handleAction)
		actionsGroup.Get("/", actionsController.handleGetActions)
		actionsGroup.Delete("/:actionName/:actionId", actionsController.handleDeleteAction)
	}

	return app
}

func (web *Web) Start() error {
	httpPort := ":" + strconv.Itoa(web.config.HttpPort)
	var err error
	go func() {
		err = web.Listen(httpPort)
		if err != nil {
			log.Error("web server err:%s", err.Error())
		}
	}()
	if err != nil {
		bus.Publish(util.WebServerStarted)
	}
	return err
}

func (web *Web) Stop() {
	err := web.App.Shutdown()
	if err != nil {
		log.Error(err.Error())
	}
	bus.Publish(util.WebServerStopped)
}

func NewDefaultWebConfig() Config {
	conf := Config{
		HttpPort:    configs.GetPorts().HTTP,
		HttpsPort:   configs.GetPorts().HTTPS,
		StaticDir:   "./dist",
		TemplateDir: "./dist",
		UploadDir:   configs.GetUploadDir(),
		LogDir:      configs.GetLogDir(),
	}
	return conf
}

// WebOption Web的函数选项
type WebOption func(*Config)

func WithHttpPort(p int) WebOption {
	return func(c *Config) {
		c.HttpPort = p
	}
}

func WithHttpsPort(p int) WebOption {
	return func(c *Config) {
		c.HttpsPort = p
	}
}

func WithStaticDir(s string) WebOption {
	return func(c *Config) {
		c.StaticDir = s
	}
}

func WithTemplateDir(t string) WebOption {
	return func(c *Config) {
		c.StaticDir = t
	}
}
