// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package messages

import "fmt"
import "encoding/json"

// Message-specific data
type MockAdapterAddDeviceRequestJsonData struct {
	// ID of the adapter
	AdapterId string `json:"adapterId" yaml:"adapterId"`

	// Description of the new device
	DeviceDescr MockAdapterAddDeviceRequestJsonDataDeviceDescr `json:"deviceDescr" yaml:"deviceDescr"`

	// ID of the new device
	DeviceId string `json:"deviceId" yaml:"deviceId"`

	// ID of the plugin
	PluginId string `json:"pluginId" yaml:"pluginId"`
}

// Description of the new device
type MockAdapterAddDeviceRequestJsonDataDeviceDescr map[string]any

// UnmarshalJSON implements json.Unmarshaler.
func (j *MockAdapterAddDeviceRequestJsonData) UnmarshalJSON(b []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["adapterId"]; !ok || v == nil {
		return fmt.Errorf("field adapterId in MockAdapterAddDeviceRequestJsonData: required")
	}
	if v, ok := raw["deviceDescr"]; !ok || v == nil {
		return fmt.Errorf("field deviceDescr in MockAdapterAddDeviceRequestJsonData: required")
	}
	if v, ok := raw["deviceId"]; !ok || v == nil {
		return fmt.Errorf("field deviceId in MockAdapterAddDeviceRequestJsonData: required")
	}
	if v, ok := raw["pluginId"]; !ok || v == nil {
		return fmt.Errorf("field pluginId in MockAdapterAddDeviceRequestJsonData: required")
	}
	type Plain MockAdapterAddDeviceRequestJsonData
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = MockAdapterAddDeviceRequestJsonData(plain)
	return nil
}

// Ask the mock adapter to add a new device
type MockAdapterAddDeviceRequestJson struct {
	// Message-specific data
	Data MockAdapterAddDeviceRequestJsonData `json:"data" yaml:"data"`

	// The message type, used by the IPC client and api to differentiate messages
	MessageType int `json:"messageType" yaml:"messageType"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *MockAdapterAddDeviceRequestJson) UnmarshalJSON(b []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if v, ok := raw["data"]; !ok || v == nil {
		return fmt.Errorf("field data in MockAdapterAddDeviceRequestJson: required")
	}
	if v, ok := raw["messageType"]; !ok || v == nil {
		return fmt.Errorf("field messageType in MockAdapterAddDeviceRequestJson: required")
	}
	type Plain MockAdapterAddDeviceRequestJson
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = MockAdapterAddDeviceRequestJson(plain)
	return nil
}
