package devices

type Capability = string

const (
	TypeString  = "string"
	TypeBoolean = "boolean"
	TypeInteger = "integer"
	TypeNumber  = "number"

	UnitHectopascal = "hectopascal"
	UnitKelvin      = "kelvin"
	UnitPercentage  = "percentage"
	UnitArcDegrees  = "arcdegrees"
	UnitCelsius     = "celsius"
	UnitLux         = "lux"
	UnitSeconds     = "seconds"
	UnitPPM         = "ppm"

	CapabilityAlarm                    Capability = "Alarm"
	CapabilityAirQualitySensor         Capability = "AirQualitySensor"
	CapabilityBarometricPressureSensor Capability = "BarometricPressureSensor"
	CapabilityBinarySensor             Capability = "BinarySensor"
	CapabilityCamera                   Capability = "Camera"
	CapabilityColorControl             Capability = "ColorControl"
	CapabilityColorSensor              Capability = "ColorSensor"
	CapabilityDoorSensor               Capability = "DoorSensor"
	CapabilityEnergyMonitor            Capability = "EnergyMonitor"
	CapabilityHumiditySensor           Capability = "HumiditySensor"
	CapabilityLeakSensor               Capability = "LeakSensor"
	CapabilityLight                    Capability = "Light"
	CapabilityLock                     Capability = "Lock"
	CapabilityMotionSensor             Capability = "MotionSensor"
	CapabilityMultiLevelSensor         Capability = "MultiLevelSensor"
	CapabilityMultiLevelSwitch         Capability = "MultiLevelSwitch"
	CapabilityOnOffSwitch              Capability = "OnOffSwitch"
	CapabilityPushButton               Capability = "PushButton"
	CapabilitySmartPlug                Capability = "SmartPlug"
	CapabilitySmokeSensor              Capability = "SmokeSensor"
	CapabilityTemperatureSensor        Capability = "TemperatureSensor"
	CapabilityThermostat               Capability = "Thermostat"
	CapabilityVideoCamera              Capability = "VideoCamera"

	OpenProperty              = "OpenProperty"
	PushedProperty            = "PushedProperty"
	SmokeProperty             = "SmokeProperty"
	TargetTemperatureProperty = "TargetTemperatureProperty"
	TemperatureProperty       = "TemperatureProperty"
	ThermostatModeProperty    = "ThermostatModeProperty"
	VideoProperty             = "VideoProperty"
	VoltageProperty           = "VoltageProperty"
)
